update Arch install

diff --git a/Arch/install b/Arch/install
--- a/Arch/install
+++ b/Arch/install
@@ -1,28 +1,29 @@
 #!/bin/bash
 # author: eleache
-# autoconfigure arch environment
-BACKUPCONFIGFILES=~/.backupconfigfiles
-mkdir $BACKUPCONFIGFILES
+# autoconfigure arch environment ## in develop
+BACKUPCONFIGFILES=~/.backup-configfiles
+USERPATH=/home/$USER
 
-function installconfig()
-{
-	cp "$2" $BACKUPCONFIGFILES
-	mv "$1" "$2"
-	echo "$1 was installed on 	$2"
+# initials
+[[ -d $BACKUPCONFIGFILES ]] || mkdir $BACKUPCONFIGFILES
+
+function install {
+	# install filename /path/to/config
+	local file="$1"
+	local ofpath="$2"
+	[[ -e $file ]] || ( echo "$file not found!" && exit )
+	[[ -e $ofpath ]] && ( cp "$ofpath" $BACKUPCONFIGFILES && echo "ok $file is rescue on $BACKUPCONFIGFILES" )
+	cp "$file" "$ofpath && echo "$file instalado en $ofpath"
 }
 
-function installscripts()
-{
-	SCRIPTSDIR=~/.myscripts
-	cd $PWD/myscripts
-	mkdir $SCRIPTSDIR
-	cp * $SCRIPTSDIR
-	cd $SCRIPTSDIR
-	chmod +x *
-	echo "$PWD installed: `ls $SCRIPTSDIR | wc -l` scripts updated"
-}
+install i3config-user $USERPATH/.config/i3/config
+install jgmenurc-user $USERPATH/.config/jgmenu/jgmenurc
+install bashrc-user $USERPATH/.bashrc
+install preprend.csv 
 
-# example
-installconfig 'bashrc-user' ~/.bashrc
-installscripts
-
+# needed sudo
+if [ $UID -eq 0  ]; then
+	install i3config-etc /etc/i3/config
+	install i3blocks-etc /etc/i3blocks.conf
+	install nanorc-etc /etc/nanorc
+fi
